services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    env_file: .env
    # depends_on:
    #   - db
