services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    ports:
      - "8080:8080"
    volumes:
      - ./app:/opt
      - go_modules:/go/pkg/mod
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    depends_on:
      - db
      - test_db

  db:
    image: postgres:16.4
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:16.4
    env_file: .env
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  pgdata:
  go_modules:
