services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    develop:
      watch:
        - action: rebuild
          path: ./app/go.mod
    ports:
      - "8080:8080"
    volumes:
      - ./app:/opt
      - go_modules:/go/pkg/mod
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  go_modules:
