name: Auto merge Dependabot PRs

on:
  pull_request:
    branches:
      - dependabot/target

jobs:
  auto_merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch metadata
        id: dependabot-metadata
        uses: dependabot/fetch-medadata@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr review "$PR_URL" --approve
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Merge PR
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge "$PR_URL" --merge --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
