name: Static analysis
on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash
        working-directory: .github/workflows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: analysis
        run: docker run --rm -v "${pwd}:${pwd}" -w "${pwd}" rhysd/actionlint:latest
