name: Unit test

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/unit_test.yml"
      - "Dockerfile"
      - "app/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Install dependencies
        run: |
          cd app
          go mod download

      - name: Check formatting
        id: gofmt
        run: |
          gofmt_output=$(gofmt -l .)
          if [ -n "$gofmt_output" ]; then
            echo "Files not formatted:"
            echo "$gofmt_output"
            exit 1
          fi

      - name: Build
        id: build
        run: go build -v app/cmd/book_order_system/main.go

      - name: Run tests
        run: go test -v ./...
