name: Unit test

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/unit_test.yml"
      - "Dockerfile"
      - "app/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: app
    env:
      TEST_DB_HOST: localhost
      TEST_DB_NAME: test_db
      TEST_DB_USER: postgres
      TEST_DB_PASSWORD: postgres

    services:
      postgres:
        image: postgres:16.4
        env:
          POSTGRES_DB: ${{ env.TEST_DB_NAME }} 
          POSTGRES_USER: ${{ env.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.TEST_DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Cache Go module
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: |
            /go/pkg/mod
            ~/.cache/go-build
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Check formatting
        id: gofmt
        run: |
          gofmt_output=$(gofmt -l .)
          if [ -n "$gofmt_output" ]; then
            echo "Files not formatted:"
            echo "$gofmt_output"
            exit 1
          fi

      - name: Build
        id: build
        run: go build -v ./cmd
        env:
          TEST_DB_HOST: ${{ env.TEST_DB_HOST }}
          TEST_DB_NAME: ${{ env.TEST_DB_NAME }}
          TEST_DB_USER: ${{ env.TEST_DB_USER }}
          TEST_DB_PASSWORD: ${{ env.TEST_DB_PASSWORD }}

      - name: Run tests
        run: go test -v ./...
